name: storm
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/BrokenShell/Storm4Dart

environment:
  sdk: ^3.3.4

dependencies:
  ffi: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
